# Generated by Django 4.0.3 on 2022-03-21 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(default='bill-name', max_length=20)),
                ('amount', models.IntegerField()),
                ('split_type', models.CharField(default='EQUAL', max_length=20)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='group-name', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField()),
                ('debt', models.IntegerField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bill')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(default='-', max_length=20)),
                ('message', models.CharField(default='-', max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('date', models.DateTimeField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bill')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SenderUser', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrentUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
