# Generated by Django 4.0.3 on 2022-03-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_activity_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bill'),
        ),
    ]
